/*
 * Guards.cpp
 *
 *  Created on: Aug 22, 2010
 *      Author: Luke
 */


#include "Guards.h"

Guards::Guards(){
// default constructor stub
}


Guards::Guards( string filename ) throw ( out_of_range, runtime_error ){
	read(filename);
}

unsigned Guards::size(){
	return guards.size();
}

Guard* Guards::getGuard(unsigned g){
	return guards[g];
}

void Guards::print( ostream &out ){
	out << "Generated by Scheduler 0.1, (c) 2010 Luke Hillman, all rights reserved.\n";
	out << "This program may not be used without express written permission from Luke Hillman.\n\n";
	out << "Guard availabilities after scheduling:\n" << endl;
	for (unsigned i = 0; i < guards.size(); i++) {
		guards[i]->print(out);
		out << "--------------------------------" << endl;
	} // for
}


void Guards::read( string filename ) throw ( out_of_range, runtime_error ){
	ifstream fin( filename.c_str() );
	if ( !fin )
		throw runtime_error("Could not locate guards.csv!");

	while(!fin.eof()){
		string type;
		Guard* g = new Guard();
		g->read(fin);
		guards.push_back(g);
		fin.get();
	} // while
}


//double Guards::getTotalAge(){

//}


Guards::~Guards(){
	//cout << "Made it to the Guards destructor..." << endl;
	//cout << "Vector size is " << guards.size() << endl;
	for (unsigned i = 0; i < guards.size(); i++) {
		//cout << "Deleting guard " << i << endl;
		delete guards[i];
	}
	//cout << "finished destructing Guards" << endl;
}
